main – Quantum transport simulator
main Program
75 statements
Source File
Uses
negf_mod
deviceHam_mod
matrix_c
omp_lib
Calls
Contents
Variables
Hii H1i Sii nx ns nen nk nb temp mu emin emax k Lx file_path calc_type rc fu nomp start finish ierr comm_size comm_rank local_NE first_local_energy
Source Code
main
Variables
Type Attributes Name Initial
type(type_matrix_complex), allocatable, dimension(:, :) :: Hii
type(type_matrix_complex), allocatable, dimension(:, :) :: H1i
type(type_matrix_complex), allocatable, dimension(:, :) :: Sii
integer :: nx
integer :: ns
integer :: nen
integer :: nk
integer :: nb
real(kind=8), dimension(2) :: temp
real(kind=8), dimension(2) :: mu
real(kind=8) :: emin
real(kind=8) :: emax
real(kind=8) :: k(2,1)
real(kind=8) :: Lx
character(len=10) :: file_path
character(len=10) :: calc_type
integer :: rc
integer :: fu
integer :: nomp
real(kind=8) :: start
real(kind=8) :: finish
integer(kind=4) :: ierr
integer(kind=4) :: comm_size
integer(kind=4) :: comm_rank
integer(kind=4) :: local_NE
integer(kind=4) :: first_local_energy
Source Code
PROGRAM main
    use omp_lib
    use negf_mod, only: negf_solve
    use matrix_c, only: type_matrix_complex, free
    use deviceHam_mod, only: devH_build_fromWannierFile, devH_build_fromCOOfile
    implicit none
    type(type_matrix_complex), allocatable, dimension(:, :)::Hii, H1i, Sii
    integer::nx, ns, nen, nk, nb
    real(8), dimension(2)::temp, mu
    real(8)::emin, emax
    real(8)::k(2, 1), Lx
    character(len=10)::file_path
    character(len=10)::calc_type
    integer::rc, fu
    integer::nomp ! openmp process number
    real(8) :: start, finish
    namelist /input/ nx, ns, temp, mu, nk, nomp, nen, emin, emax, nb, calc_type
    ! MPI variables
    integer(kind=4) ierr
    integer(kind=4) comm_size
    integer(kind=4) comm_rank
    integer(kind=4) local_NE
    integer(kind=4) first_local_energy
!    include "mpif.h"
!    call MPI_Init(ierr)
!    call MPI_Comm_size(MPI_COMM_WORLD, comm_size, ierr)
!    call MPI_Comm_rank(MPI_COMM_WORLD, comm_rank, ierr)
!    call MPI_Barrier(MPI_COMM_WORLD, ierr)
    comm_size = 1
    comm_rank=0
    if (comm_rank == 0) then
        print *, 'Comm Size =', comm_size
    else
        print *, 'Comm Rank =', comm_rank
    end if
    ! default values
    nx = 5
    ns = 3
    nb = 10
    temp = 300.0d0
    mu = 0.0d0
    nk = 1
    nen = 100
    emin = -10.0d0
    emax = 5.0d0
    k = 0.0d0
    nomp = 4
    calc_type = 'w90'
    print *, 'read input'
    ! Check whether file exists.
    file_path = 'input'
    inquire (file=file_path, iostat=rc)
    if (rc /= 0) then
        write (*, '("Warn: input file ", a, " does not exist")') file_path
    else
        ! Open and read Namelist file.
        open (action='read', file=file_path, iostat=rc, newunit=fu)
        read (nml=input, iostat=rc, unit=fu)
        close (fu)
    end if
    call omp_set_num_threads(nomp)
    local_NE = nen/comm_size
    first_local_energy = local_NE*comm_rank + 1
    if (comm_rank == 0) then
        print *, "read ham"
    endif
    if (calc_type == 'w90') then
        call devH_build_fromWannierFile('ham_dat', Hii, H1i, Sii, nx, ns, nb, nk, &
                                    k, Lx)
    else
        call devH_build_fromCOOfile('h_dat', Hii, H1i, Sii, (/0,0/), (/nb,nb/), nx, &
            use0index = .true., iscomplex = .false., threshold = 1d-10, blocksize=nb)
    endif
    if (comm_rank == 0) then
        print *, "start NEGF solver ... "
    endif
    start = omp_get_wtime()
    call negf_solve(nx, nen, nk, emin, emax, Hii, H1i, Sii, temp, mu, &
                    comm_size, comm_rank, local_NE, first_local_energy, NB, &
                    NS, Lx)
    finish = omp_get_wtime()
    if (comm_rank == 0) then
        print *, "Total Work took seconds", finish - start
    endif
    call free(Hii)
    call free(H1i)
    call free(Sii)
    !deallocate (Hii, H1i, Sii)
    ! call MPI_FINALIZE( ierr )
END PROGRAM main
Call graph
main calls devh_build_fromcoofile, devh_build_fromwannierfile, negf_solve
devh_build_fromwannierfile calls w90_free_memory, w90_load_from_file, w90_mat_def
negf_solve calls cuda_rgf_constblocksize, cuda_rgf_finish, cuda_rgf_init, write_spectrum_summed_over_k
cuda_rgf_constblocksize calls omp_get_wtime, zaxpy, zcopy, zgemm, zgetrf, zgetrs, zscal
w90_load_from_file calls cross, norm