array_power – Quantum transport simulator
array_power Function
26 statements
Source File
public function array_power(A, n) result(C)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: A(:,:)
integer, intent(in) :: n
Return Value complex(kind=8), (size(A,1),size(A,1))
Calls
Called by
Contents
Source Code
array_power
Source Code
    function array_power(A, n) result(C)
        implicit none
        complex(8), intent(in):: A(:, :)
        integer, intent(in) :: n
        complex(8) :: B(size(A, 1), size(A, 1))
        complex(8) :: C(size(A, 1), size(A, 1))
        integer :: ii
        if (n > 0) then
            B = A
            do ii = 2, n
                B = B.m.A
            end do
            C = B
        elseif (n == 0) then
            C = array_eye(size(A, dim=1))
        elseif (n == -1) then
            C = array_inverse(A)
        else
            C = array_inverse(A)
            B = C
            do ii = 2, -n
                B = B.m.C
            end do
            C = B
        end if
    end function array_power
Call graph
array_power calls array_eye, array_inverse
array_inverse calls zgetrf, zgetri
operator(ASTERISKASTERISK) calls array_power