array_times_array – Quantum transport simulator
array_times_array Function
47 statements
Source File
public pure function array_times_array(A, B, trA, trB, cjA, cjB) result(C)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: A(:,:)
complex(kind=8), intent(in) :: B(:,:)
logical(kind=4), intent(in) :: trA
logical(kind=4), intent(in) :: trB
logical(kind=4), intent(in), optional :: cjA
logical(kind=4), intent(in), optional :: cjB
Return Value complex(kind=8), (size(A,merge(2,1,trA)),size(B,merge(1,2,trB)))
Called by
Contents
Source Code
array_times_array
Source Code
    pure function array_times_array(A, B, trA, trB, cjA, cjB) result(C)
        implicit none
        complex(8), intent(in) :: A(:, :), B(:, :)
        LOGICAL(KIND=4), intent(in):: trA, trB
        complex(8) :: C(size(A, merge(2, 1, trA)), size(B, merge(1, 2, trB)))
        LOGICAL(KIND=4), intent(in), optional:: cjA, cjB
        integer :: lda, ldb, k, m, kb, n
        character :: ctrA, ctrB
        interface
            pure subroutine ZGEMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
                COMPLEX(8), intent(in):: ALPHA, BETA
                INTEGER, intent(in):: K, LDA, LDB, LDC, M, N
                CHARACTER, intent(in):: TRANSA, TRANSB
                COMPLEX(8), intent(in):: A(lda, *), B(ldb, *)
                COMPLEX(8), intent(inout):: C(ldc, *)
            end subroutine ZGEMM
        end interface
        lda = size(A, 1)
        ldb = size(B, 1)
        if (.not. trA) then
            k = size(A, 2)
            m = size(A, 1)
            ctrA = 'n'
        else
            k = size(A, 1)
            m = size(A, 2)
            if (present(cjA) .and. cjA) then
                ctrA = 'c'
            else
                ctrA = 't'
            end if
        end if
        if (.not. trB) then
            kb = size(B, 1)
            n = size(B, 2)
            ctrB = 'n'
        else
            kb = size(B, 2)
            n = size(B, 1)
            if (present(cjB) .and. cjB) then
                ctrB = 'c'
            else
                ctrB = 't'
            end if
        end if
        call zgemm(ctrA, ctrB, m, n, k, dcmplx(1.0d0, 0.0d0), A, lda, B, ldb, dcmplx(0.0d0, 0.0d0), C, m)
    end function array_times_array
Call graph
array_dagger_times_array calls array_times_array
array_times_array_dagger calls array_times_array
array_times_array_simple calls array_times_array
operator(.dm.) calls array_dagger_times_array
operator(.m.) calls array_times_array_simple
operator(.md.) calls array_times_array_dagger