array_inverse – Quantum transport simulator
array_inverse Function
25 statements
Source File
public function array_inverse(A)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: A(:,:)
Return Value complex(kind=8), dimension(size(A, dim=1), size(A, dim=1))
Calls
Called by
Contents
Source Code
array_inverse
Source Code
    function array_inverse(A) ! for General matrix
        implicit none
        complex(8), intent(in) :: A(:, :)
        integer :: info, n
        integer :: ipiv(size(A, 1))
        complex(8), dimension(size(A, dim=1), size(A, dim=1)) :: array_inverse
        complex(8), allocatable :: work(:, :)
        n = size(A, 1)
        if (n /= size(A, 2)) then
            print *, '@array_inverse, size not square', n, size(A, 2)
            call abort()
        end if
        array_inverse(:, :) = A(:, :)
        allocate (work(n*n, n*n))
        call zgetrf(n, n, array_inverse, n, ipiv, info)
        if (info .ne. 0) then
            print *, '@array_inverse ZGETRF fails with INFO=', info
            call abort()
        end if
        call zgetri(n, array_inverse, n, ipiv, work, n*n, info)
        if (info .ne. 0) then
            print *, '@array_inverse ZGETRI fails with INFO=', info
            call abort()
        end if
    end function array_inverse
Call graph
array_inverse calls zgetrf, zgetri
array_power calls array_inverse
rgf_variableblock_backward calls array_inverse
operator(ASTERISKASTERISK) calls array_power