corr1d2 – Quantum transport simulator
corr1d2 Function
32 statements
Source File
public function corr1d2(n, X, Y, method) result(Z)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
complex(kind=8), intent(in) :: X(n)
complex(kind=8), intent(in) :: Y(n)
character(len=*), intent(in) :: method
Return Value complex(kind=8), (n)
Calls
Contents
Source Code
corr1d2
Source Code
    function corr1d2(n, X, Y, method) result(Z)
        integer, intent(in)::n
        character(len=*), intent(in)::method
        complex(8), intent(in)::X(n), Y(n)
        complex(8)::Z(n)
        complex(8), allocatable, dimension(:) :: X_, Y_, Z_
        integer::i, ie
        select case (trim(method))
        case ('index')
            Z = czero
            do i = -n/2 + 1, n/2 - 1
                do ie = max(i + 1, 1), min(n, n + i)
                    Z(i + n/2) = Z(i + n/2) + X(ie)*Y(ie - i)
                end do
            end do
        case ('simple')
            do i = -n/2 + 1, n/2 - 1
                Z(i + n/2) = sum(X(max(1, 1 + i):min(n + i, n))*Y(max(1 - i, 1):min(n, n - i)))
            end do
        case ('fft')
            allocate (X_(n*2 - 1))
            allocate (Y_(n*2 - 1))
            allocate (Z_(n*2 - 1))
            X_ = czero ! pad by zero
            Y_ = czero
            X_(1:n) = X
            Y_(1:n) = Y(n:1:-1)
            call do_mkl_dfti_conv(n*2 - 1, X_, Y_, Z_)
            Z = Z_(n - n/2:n + n/2 - 1)
            deallocate (X_, Y_, Z_)
        end select
    end function corr1d2
Call graph
corr1d2 calls do_mkl_dfti_conv
do_mkl_dfti_conv calls dfticommitdescriptor, dfticomputebackward, dfticomputeforward, dfticreatedescriptor, dftifreedescriptor, dftisetvalue