cuda_rgf_constblocksize – Quantum transport simulator
cuda_rgf_constblocksize Subroutine
215 statements
Source File
public subroutine cuda_rgf_constblocksize(nm, nx, En, mul, mur, TEMPl, TEMPr, Hii, H1i, Sii, sigma_lesser_ph, sigma_r_ph, G_r, G_lesser, G_greater, Jdens, tr, tre)
!$omp target exit data map(delete:H10,G00,A,sigmal,S00,sig2,B) ! G<_i+1,i
! G<_i,i+1 ! G_i,i+1
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nm
lenght of the device
integer, intent(in) :: nx
lenght of the device
real(kind=dp), intent(in) :: En
real(kind=dp), intent(in) :: mul(:,:)
real(kind=dp), intent(in) :: mur(:,:)
real(kind=dp), intent(in) :: TEMPl(:,:)
real(kind=dp), intent(in) :: TEMPr(:,:)
type(type_matrix_complex), intent(in) :: Hii(nx)
type(type_matrix_complex), intent(in) :: H1i(nx+1)
type(type_matrix_complex), intent(in) :: Sii(nx)
type(type_matrix_complex), intent(in) :: sigma_lesser_ph(nx)
type(type_matrix_complex), intent(in) :: sigma_r_ph(nx)
type(type_matrix_complex), intent(inout) :: G_r(nx)
type(type_matrix_complex), intent(inout) :: G_lesser(nx)
type(type_matrix_complex), intent(inout) :: G_greater(nx)
type(type_matrix_complex), intent(inout) :: Jdens(nx)
real(kind=dp), intent(out) :: tr
real(kind=dp), intent(out) :: tre
Calls
Called by
Contents
Source Code
cuda_rgf_constblocksize
Source Code
subroutine cuda_rgf_constblocksize(nm, nx, En, mul, mur, TEMPl, TEMPr, Hii, H1i, Sii, sigma_lesser_ph, &
    sigma_r_ph, G_r, G_lesser, G_greater, Jdens, tr, tre)
    type(type_matrix_complex), intent(in) :: Hii(nx), H1i(nx + 1), Sii(nx), sigma_lesser_ph(nx), sigma_r_ph(nx)
    real(dp), intent(in) :: En, mul(:, :), mur(:, :), TEMPr(:, :), TEMPl(:, :)
    integer, intent(in) :: nx,nm !! lenght of the device
    type(type_matrix_complex), intent(inout):: G_greater(nx), G_lesser(nx), G_r(nx), Jdens(nx)
    real(dp), intent(out) :: tr, tre
    ! ----
    COMPLEX(dp) :: z
    integer::i,j,k,l,info1,info2,ii
    real(dp)::tim, start, finish, start_0
    COMPLEX(dp), allocatable :: Gl(:,:,:),Gln(:,:,:),Glp(:,:,:) ! left-connected green function
    complex(dp), parameter :: alpha = cmplx(1.0d0,0.0d0)
    complex(dp), parameter :: beta  = cmplx(0.0d0,0.0d0)
    !
    z=dcmplx(En,0.0d-6)
    Id=dcmplx(0.0d0,0.0d0)
    forall (ii=1:nm) Id(ii,ii)=1.0d0
    !
    allocate(Gl(nm,nm,nx))
    allocate(Gln(nm,nm,nx))
    allocate(Glp(nm,nm,nx))
    !
    !
    Gln=0.0d0
    Glp=0.0d0
    Gl=0.0d0
    do l=1,nx
        G_r(l)%m=0.0d0
        G_lesser(l)%m=0.0d0
        G_greater(l)%m=0.0d0
        Jdens(l)%m=0.0d0
    enddo
    !
    start = omp_get_wtime()
    start_0=start
    !
    ! self energy on the left contact
    S00(:,:)=Sii(1)%m
    sig(:,:)=sigma_r_ph(1)%m
    !$omp target update to(sig,S00)
    !$omp target data use_device_ptr(sig,S00,B)
    call zgemm('n','n',nm,nm,nm,alpha,sig,nm,S00,nm,beta,B,nm)
    !$omp end target data
    !$omp target update from(B)
    H00(:,:)=Hii(1)%m+B(:,:)
    H10(:,:)=H1i(1)%m
    !
    call sancho(nm,En,S00,H00,transpose(conjg(H10)),G00,GBB)
    !
    sig2(:,:)=sigma_lesser_ph(1)%m
    !
    !$omp target update to(H10,G00,sigmal,S00,sig2)
    !$omp target data use_device_ptr(H10,G00,A,sigmal,S00,sig2,B)
    call zgemm('n','n',nm,nm,nm,alpha,H10,nm,G00,nm,beta,A,nm)
    call zgemm('n','c',nm,nm,nm,alpha,A,nm,H10,nm,beta,sigmal,nm)
    call zgemm('n','n',nm,nm,nm,alpha,sig2,nm,S00,nm,beta,B,nm)
    !$omp end target data
    !$omp target update from(B,sigmal)
    !!!$omp target exit data map(delete:H10,G00,A,sigmal,S00,sig2,B)
    sig(:,:)=-(sigmal(:,:)-transpose(conjg(sigmal(:,:))))*ferm((En-mul)/(BOLTZ*TEMPl))+B(:,:)
    A=z*S00-H00-sigmal
    !
    ! call invert(A,nm)
    !$omp target update to(A, Id)
    !$omp target data use_device_ptr(A,ipiv,work,Id)
    call zcopy(nm*nm,Id,1,work,1)
    call zgetrf(nm, nm, A, nm, ipiv, info1)
    call zgetrs('n',nm, nm, A, nm, ipiv, work, nm, info2)
    call zcopy(nm*nm,work,1,A,1)
    !$omp end target data
    !$omp target update from(A)
    Gl(:,:,1)=A(:,:)
    !
    !$omp target update to(sig,A)
    !$omp target data use_device_ptr(A,sig,B,C)
    call zgemm('n','n',nm,nm,nm,alpha,A,nm,sig,nm,beta,B,nm)
    call zgemm('n','c',nm,nm,nm,alpha,B,nm,A,nm,beta,C,nm)
    !$omp end target data
    !$omp target update from(C)
    Gln(:,:,1)=C(:,:)
    !
    finish = omp_get_wtime()
    print *, "---- left contact took seconds", finish - start
    start = finish
    !
    Do l=2,nx-1
        H00(:,:)=Hii(l)%m+sigma_r_ph(l)%m
        H10(:,:)=H1i(l)%m
        G00(:,:)=Gl(:,:,l-1)
        sig=Gln(:,:,l-1)
        sig2=sigma_lesser_ph(l)%m
        S00(:,:)=Sii(l)%m
        !
        !$omp target update to(H00,H10,G00,S00,sig,sig2)
        !$omp target data use_device_ptr(H10,G00,B,C,A,H00,S00,Gn,sig,sig2,work,ipiv,Id)
        call zgemm('n','n',nm,nm,nm,alpha,H10,nm,G00,nm,beta,B,nm)
        call zgemm('n','c',nm,nm,nm,alpha,B,nm,H10,nm,beta,C,nm)
        call zcopy(nm*nm,C,1,A,1)
        call zaxpy(nm*nm,alpha,H00,1,A,1)
        call zaxpy(nm*nm,-z,S00,1,A,1)
        call zscal(nm*nm,-alpha,A,1)
        ! A=z*S00-H00-C
        !
        ! call invert(A,nm)
        call zcopy(nm*nm,Id,1,work,1)
        call zgetrf(nm, nm, A, nm, ipiv, info1)
        call zgetrs('n',nm, nm, A, nm, ipiv, work, nm, info2)
        call zcopy(nm*nm,work,1,A,1)
        call zcopy(nm*nm,A,1,G00,1)
        !
        call zgemm('n','n',nm,nm,nm,alpha,H10,nm,sig,nm,beta,B,nm)
        call zgemm('n','c',nm,nm,nm,alpha,B,nm,H10,nm,beta,C,nm)
        call zgemm('n','n',nm,nm,nm,alpha,sig2,nm,S00,nm,beta,B,nm)
        !
        ! C(:,:)=C(:,:)+B(:,:)
        call zaxpy(nm*nm,alpha,B,1,C,1)
        !
        call zgemm('n','n',nm,nm,nm,alpha,A,nm,C,nm,beta,B,nm)
        call zgemm('n','c',nm,nm,nm,alpha,B,nm,A,nm,beta,Gn,nm)
        !$omp end target data
        !$omp target update from(Gn,G00)
        Gln(:,:,l)=Gn(:,:)
        Gl(:,:,l)=G00(:,:)
        if (info1 .ne. 0) then
            print *, 'SEVERE warning: zgetrf failed, info=', info1
            call abort()
        end if
        if (info2 .ne. 0) then
            print *, 'SEVERE warning: zgetri failed, info=', info2
            call abort()
        end if
    enddo
    finish = omp_get_wtime()
    print *, "---- first pass took seconds", finish - start
    start = finish
    ! self energy on the right contact
    S00(:,:)=Sii(nx)%m
    sig2(:,:)=sigma_r_ph(nx)%m
    !$omp target update to(S00,sig2)
    !$omp target data use_device_ptr(S00,sig2,B)
    call zgemm('n','n',nm,nm,nm,alpha,sig2,nm,S00,nm,beta,B,nm)
    !$omp end target data
    !$omp target update to(B)
    H00(:,:)=Hii(nx)%m+B(:,:)
    H10(:,:)=H1i(nx)%m
    !
    call sancho(NM,En,S00,H00,H10,G00,GBB)
    !
    Glii=Gl(:,:,nx-1)
    !$omp target update to(H10,G00,Glii)
    !$omp target data use_device_ptr(H10,G00,A,sigmar,G00,B,C,Glii)
    call zgemm('c','n',nm,nm,nm,alpha,H10,nm,G00,nm,beta,A,nm)
    call zgemm('n','n',nm,nm,nm,alpha,A,nm,H10,nm,beta,sigmar,nm)
    !
    call zgemm('n','n',nm,nm,nm,alpha,H10,nm,Glii,nm,beta,B,nm)
    call zgemm('n','c',nm,nm,nm,alpha,B,nm,H10,nm,beta,C,nm)
    !$omp end target data
    !$omp target update from(C,sigmar)
    !
    G00=z*S00-H00-sigmar-C
    !
    ! call invert(G00,nm)
    !$omp target update to(G00, work)
    !$omp target data use_device_ptr(G00,ipiv,work,Id)
    call zcopy(nm*nm,Id,1,work,1)
    call zgetrf(nm, nm, G00, nm, ipiv, info1)
    call zgetrs('n',nm, nm, G00, nm, ipiv, work, nm, info2)
    call zcopy(nm*nm,work,1,G00,1)
    !$omp end target data
    !$omp target update from(G00)
    !
    G_r(nx)%m=G00(:,:)!dcmplx(0.0d0,1.0d0)*(G00(:,:)-transpose(conjg(G00(:,:))))
    sig=Gln(:,:,nx-1)
    sig2=sigma_lesser_ph(nx)%m
    !$omp target update to(sig,sig2,S00)
    !$omp target data use_device_ptr(H10,sig,B,C,sig2,S00)
    call zgemm('n','n',nm,nm,nm,alpha,H10,nm,sig,nm,beta,B,nm)
    call zgemm('n','c',nm,nm,nm,alpha,B,nm,H10,nm,beta,C,nm)  ! C=H10 Gl< H01
    call zgemm('n','n',nm,nm,nm,alpha,sig2,nm,S00,nm,beta,B,nm)
    !$omp end target data
    !$omp target update from(B)
    ! B=Sig< S00
    sig(:,:)=-(sigmar(:,:)-transpose(conjg(sigmar(:,:))))*ferm((En-mur)/(BOLTZ*TEMPl))+C(:,:)+B(:,:)
    !
    !$omp target update to(G00,sig)
    !$omp target data use_device_ptr(G00,sig,Gn,B)
    call zgemm('n','n',nm,nm,nm,alpha,G00,nm,sig,nm,beta,B,nm)
    call zgemm('n','c',nm,nm,nm,alpha,B,nm,G00,nm,beta,Gn,nm)
    !$omp end target data
    !$omp target update from(Gn)
    ! G<00 = G00 sig< G00'
    G_lesser(nx)%m=Gn(:,:)
    Gp(:,:)=Gn(:,:)+(G00(:,:)-transpose(conjg(G00(:,:))))
    G_greater(nx)%m=Gp(:,:)
    A=-(sigmar-transpose(conjg(sigmar)))*ferm((En-mur)/(BOLTZ*TEMPl))
    !
    !$omp target update to(A,Gp)
    !$omp target data use_device_ptr(A,Gp,B)
    call zgemm('n','n',nm,nm,nm,alpha,A,nm,Gp,nm,beta,B,nm)
    !$omp end target data
    !$omp target update from(B)
    !
    A=-(sigmar-transpose(conjg(sigmar)))*(ferm((En-mur)/(BOLTZ*TEMPl))-1.0d0)
    !
    !$omp target update to(A,Gn)
    !$omp target data use_device_ptr(A,Gn,C)
    call zgemm('n','n',nm,nm,nm,alpha,A,nm,Gn,nm,beta,C,nm)
    !$omp end target data
    !$omp target update from(C)
    tim=0.0d0
    do i=1,nm
        do j=i,i!1,nm
            tim=tim-dble(B(i,j)-C(i,j))
        enddo
    enddo
    tr=tim
    ! transmission
    !-------------------------
    finish = omp_get_wtime()
    print *, "---- right contact took seconds", finish - start
    start = finish
    do l=nx-1,1,-1
        H10(:,:)=H1i(l)%m
        A=Gn
        Glii=Gl(:,:,l)
        Glpii=Glp(:,:,l)
        Glnii=Gln(:,:,l)
        !$omp target update to(H10,A,Glii,Glpii,Glnii)
        !$omp target data use_device_ptr(H10,G00,B,C,A,D,H00,S00,Glii,Glpii,Glnii,cur,Gn,Gp,GN0)
        !
        call zgemm('n','c',nm,nm,nm,alpha,H10,nm,Glii,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,A,nm,B,nm,beta,C,nm)
        call zcopy(nm*nm,Glnii,1,A,1)
        ! A=Gln(:,:,l)
        call zgemm('n','n',nm,nm,nm,alpha,H10,nm,A,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,G00,nm,B,nm,beta,A,nm)
        call zcopy(nm*nm,C,1,B,1)
        call zaxpy(nm*nm,alpha,A,1,B,1)
        ! B=C+A
        call zgemm('c','n',nm,nm,nm,alpha,H10,nm,B,nm,beta,A,nm)      !!! G<_i+1,i
        call zcopy(nm*nm,A,1,cur,1)
        ! cur=dble(A(:,:))
        !-------------------------
        call zcopy(nm*nm,Gn,1,A,1)
        ! A=Gn
        call zgemm('n','c',nm,nm,nm,alpha,Glii,nm,H10,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,B,nm,A,nm,beta,C,nm)   ! g H10 G<
        call zcopy(nm*nm,Glnii,1,A,1)
        ! A=Glnii
        call zgemm('n','c',nm,nm,nm,alpha,A,nm,H10,nm,beta,B,nm)
        call zgemm('n','c',nm,nm,nm,alpha,B,nm,G00,nm,beta,A,nm) ! g< H10 G'
        call zcopy(nm*nm,C,1,B,1)
        call zaxpy(nm*nm,alpha,A,1,B,1)
        ! B=C+A
        call zgemm('n','n',nm,nm,nm,alpha,H10,nm,B,nm,beta,A,nm)      !!! G<_i,i+1
        call zaxpy(nm*nm,-alpha,A,1,cur,1)
        ! cur=cur-dble(A(:,:))
        !-------------------------
        call zcopy(nm*nm,Glii,1,D,1)
        ! D(:,:)= Glii
        call zgemm('n','c',nm,nm,nm,alpha,Glii,nm,H10,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,B,nm,G00,nm,beta,GN0,nm)      !!! G_i,i+1
        call zgemm('n','n',nm,nm,nm,alpha,GN0,nm,H10,nm,beta,A,nm)
        call zgemm('n','n',nm,nm,nm,alpha,A,nm,Glii,nm,beta,C,nm)
        call zcopy(nm*nm,Glii,1,G00,1)
        call zaxpy(nm*nm,alpha,C,1,G00,1)
        ! G00(:,:)=Glii+C(:,:)                                       !!! G_i,i
        !-------------------------
        ! A(:,:)=Gn(:,:)
        call zcopy(nm*nm,Gn,1,A,1)
        call zgemm('n','c',nm,nm,nm,alpha,Glii,nm,H10,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,B,nm,A,nm,beta,C,nm)
        call zgemm('n','n',nm,nm,nm,alpha,C,nm,H10,nm,beta,A,nm)
        call zgemm('n','c',nm,nm,nm,alpha,A,nm,Glii,nm,beta,C,nm)
        call zcopy(nm*nm,Glnii,1,Gn,1)
        call zaxpy(nm*nm,alpha,C,1,Gn,1)
        ! Gn(:,:)= Glnii + C(:,:)
        call zcopy(nm*nm,Glnii,1,A,1)
        ! A(:,:)=Glnii
        call zgemm('n','n',nm,nm,nm,alpha,GN0,nm,H10,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,B,nm,A,nm,beta,C,nm)
        call zaxpy(nm*nm,alpha,C,1,Gn,1)
        ! Gn(:,:)= Gn(:,:)+C(:,:)!
        call zgemm('n','c',nm,nm,nm,alpha,A,nm,H10,nm,beta,B,nm)
        call zgemm('n','c',nm,nm,nm,alpha,B,nm,GN0,nm,beta,C,nm)
        call zaxpy(nm*nm,alpha,C,1,Gn,1)
        ! Gn(:,:)= Gn(:,:)+C(:,:)!                          !!! G<_i,i
        !-------------------------
        ! A(:,:)=Gp(:,:)
        call zcopy(nm*nm,Gp,1,A,1)
        call zgemm('n','c',nm,nm,nm,alpha,Glii,nm,H10,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,B,nm,A,nm,beta,C,nm)
        !
        call zgemm('n','n',nm,nm,nm,alpha,C,nm,H10,nm,beta,A,nm)
        call zgemm('n','c',nm,nm,nm,alpha,A,nm,Glii,nm,beta,C,nm)
        !
        call zcopy(nm*nm,Glpii,1,Gp,1)
        call zaxpy(nm*nm,alpha,C,1,Gp,1)
        ! Gp(:,:)= Glpii + C(:,:)
        ! A(:,:)=Glp(:,:,l)
        call zcopy(nm*nm,Glpii,1,A,1)
        call zgemm('n','n',nm,nm,nm,alpha,GN0,nm,H10,nm,beta,B,nm)
        call zgemm('n','n',nm,nm,nm,alpha,B,nm,A,nm,beta,C,nm)
        !
        call zaxpy(nm*nm,alpha,C,1,Gp,1)
        ! Gp(:,:)= Gp(:,:)+C(:,:)!
        call zgemm('n','c',nm,nm,nm,alpha,A,nm,H10,nm,beta,B,nm)
        call zgemm('n','c',nm,nm,nm,alpha,B,nm,GN0,nm,beta,C,nm)
        call zaxpy(nm*nm,alpha,C,1,Gp,1)
        ! Gp(:,:)= Gp(:,:)+C(:,:)!                          !!! G>_i,i
        !-------------------------
        !$omp end target data
        !$omp target update from(Gn,Gp,G00,cur)
        G_lesser(l)%m=Gn(:,:)
        G_greater(l)%m=Gp(:,:)
        G_r(l)%m=G00(:,:)
        Jdens(l)%m=cur
    enddo
    !
    finish = omp_get_wtime()
    print *, "---- second pass took seconds", finish - start
    start = finish
    !
    Gp(:,:)=Gn(:,:)+(G00(:,:)-transpose(conjg(G00(:,:))))
    A=-(sigmal-transpose(conjg(sigmal)))*ferm((En-mul)/(BOLTZ*TEMPr))
    !
    !$omp target update to(A,Gp)
    !$omp target data use_device_ptr(A,Gp,B)
    call zgemm('n','n',nm,nm,nm,alpha,A,nm,Gp,nm,beta,B,nm)
    !$omp end target data
    !$omp target update from(B)
    !
    A=-(sigmal-transpose(conjg(sigmal)))*(ferm((En-mul)/(BOLTZ*TEMPr))-1.0d0)
    !$omp target update to(A,Gn)
    !$omp target data use_device_ptr(A,Gn,C)
    call zgemm('n','n',nm,nm,nm,alpha,A,nm,Gn,nm,beta,C,nm)
    !$omp end target data
    !$omp target update from(C)
    !
    tim=0.0d0
    do i=1,nm
        tim=tim+dble(B(i,i)-C(i,i))
    enddo
    tre=tim
    !
    deallocate(Gl)
    deallocate(Gln)
    deallocate(Glp)
    print *, "RGF took seconds", finish - start_0
end subroutine cuda_rgf_constblocksize
Call graph
cuda_rgf_constblocksize calls omp_get_wtime, zaxpy, zcopy, zgemm, zgetrf, zgetrs, zscal
negf_solve calls cuda_rgf_constblocksize
main calls negf_solve