devH_build_fromWannierFile – Quantum transport simulator
devH_build_fromWannierFile Subroutine
53 statements
Source File
public subroutine devH_build_fromWannierFile(fname, Hii, H1i, Sii, nx, nslab, nband, nk, k, length_x, lreorder_axis, axis)
Uses
wannierHam3d
matrix_c
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
input text file name
type(type_matrix_complex), intent(inout), dimension(:, :), allocatable :: Hii
Hamiltonian blocks
type(type_matrix_complex), intent(inout), dimension(:, :), allocatable :: H1i
Hamiltonian blocks
type(type_matrix_complex), intent(inout), dimension(:, :), allocatable :: Sii
overlap matrix blocks
integer, intent(in) :: nx
number of slabs
integer, intent(in) :: nslab
number of cells per slab
integer, intent(out) :: nband
number of bands/orbitals per cell (from wannier90)
integer, intent(in) :: nk
real(kind=dp), intent(in) :: k(2,nk)
real(kind=dp), intent(out) :: length_x
logical, intent(in), optional :: lreorder_axis
whether to reorder axis
integer, intent(in), optional :: axis(3)
permutation order
Calls
Called by
Contents
Source Code
devH_build_fromWannierFile
Source Code
    subroutine devH_build_fromWannierFile(fname, Hii, H1i, Sii, nx, nslab, nband, nk, k, length_x, lreorder_axis, axis)
        use matrix_c, only: type_matrix_complex, malloc
        use wannierHam3d, only: w90_load_from_file, w90_free_memory, w90_MAT_DEF, nb, Lx
        character(len=*), intent(in)        :: fname !! input text file name
        logical, intent(in), optional :: lreorder_axis !! whether to reorder axis
        integer, intent(in), optional :: axis(3) !! permutation order
        integer, intent(in)::nx !! number of slabs
        integer, intent(in):: nslab !! number of cells per slab
        integer, intent(out):: nband !! number of bands/orbitals per cell (from wannier90)
        type(type_matrix_complex), dimension(:, :), intent(inout), allocatable::Hii, H1i !! Hamiltonian blocks
        type(type_matrix_complex), dimension(:, :), intent(inout), allocatable::Sii !! overlap matrix blocks
        real(dp), intent(in)::k(2, nk)
        real(dp), intent(out)::length_x
        integer, intent(in)::nk
        ! ----
        complex(dp), allocatable, dimension(:, :)::H00, H10
        real(dp)::kx, ky, kz
        integer::nm, i, im, ik
        integer, dimension(2, nx + 1)::nmm
        print *,"read w90"
        open (unit=10, file=trim(fname), status='unknown')
        call w90_load_from_file(10, lreorder_axis, axis)
        close (10)
        print *,"read w90 DONE"
        nm = nb*nslab
        nband = nb
        length_x = Lx
        nmm = nm
        allocate (H00(nm, nm))
        allocate (H10(nm, nm))
        kx = 0.0d0
        !
        allocate (Hii(nx, nk))
        allocate (H1i(nx + 1, nk))
        allocate (Sii(nx, nk))
        do ik = 1, nk
            ky = k(1, ik)
            kz = k(2, ik)
            call w90_MAT_DEF(H00, H10, kx, ky, kz, nslab)
            !
            call malloc(Hii(:, ik), nx, nmm(:, 1:nx))
            call malloc(Sii(:, ik), nx, nmm(:, 1:nx))
            call malloc(H1i(:, ik), nx + 1, nmm)
            !
            do i = 1, nx
                Hii(i, ik)%m = H00
                H1i(i, ik)%m = H10
                Sii(i, ik)%m = dcmplx(0.0d0, 0.0d0)
                do im = 1, nm
                    Sii(i, ik)%m(im, im) = 1.0d0
                end do
            end do
            H1i(nx + 1, ik)%m = H10
        end do
        deallocate (H00, H10)
        call w90_free_memory()
    end subroutine devH_build_fromWannierFile
Call graph
devh_build_fromwannierfile calls w90_free_memory, w90_load_from_file, w90_mat_def
w90_load_from_file calls cross, norm
main calls devh_build_fromwannierfile