do_mkl_dfti_conv – Quantum transport simulator
do_mkl_dfti_conv Subroutine
17 statements
Source File
public subroutine do_mkl_dfti_conv(n, X_in, Y_in, Z_out)
Uses
MKL_DFTI
Arguments
Type Intent Optional Attributes Name
integer :: n
complex(kind=8) :: X_in(n)
complex(kind=8) :: Y_in(n)
complex(kind=8) :: Z_out(n)
Calls
Called by
Contents
Source Code
do_mkl_dfti_conv
Source Code
    subroutine do_mkl_dfti_conv(n, X_in, Y_in, Z_out)
! 1D complex to complex
        Use MKL_DFTI
        integer :: n
        Complex(8) :: X_in(n), Y_in(n), Z_out(n)
        Complex(8) :: X_out(n), Y_out(n), Z_in(n)
        type(DFTI_DESCRIPTOR), POINTER :: My_Desc1_Handle, My_Desc2_Handle
        Integer :: Status
! Perform a complex to complex transform
        Status = DftiCreateDescriptor(My_Desc1_Handle, DFTI_DOUBLE, DFTI_COMPLEX, 1, n)
        Status = DftiSetValue(My_Desc1_Handle, DFTI_PLACEMENT, DFTI_NOT_INPLACE)
        Status = DftiCommitDescriptor(My_Desc1_Handle)
        Status = DftiComputeForward(My_Desc1_Handle, X_in, X_out)
        Status = DftiComputeForward(My_Desc1_Handle, Y_in, Y_out)
!
        Z_in(:) = X_out(:)*Y_out(:)
!
        Status = DftiComputeBackward(My_Desc1_Handle, Z_in, Z_out)
        Status = DftiFreeDescriptor(My_Desc1_Handle)
        Z_out(:) = Z_out(:)/dble(n)
    end subroutine do_mkl_dfti_conv
Call graph
do_mkl_dfti_conv calls dfticommitdescriptor, dfticomputebackward, dfticomputeforward, dfticreatedescriptor, dftifreedescriptor, dftisetvalue
conv1d calls do_mkl_dfti_conv
conv1d2 calls do_mkl_dfti_conv
corr1d calls do_mkl_dfti_conv
corr1d2 calls do_mkl_dfti_conv