invert – Quantum transport simulator
invert Subroutine
21 statements
Source File
public subroutine invert(A, nn)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(nn, nn) :: A
integer :: nn
Calls
Called by
Contents
Source Code
invert
Source Code
    subroutine invert(A, nn)
        integer :: info, nn
        integer, dimension(:), allocatable :: ipiv
        complex(8), dimension(nn, nn), intent(inout) :: A
        complex(8), dimension(:), allocatable :: work
        allocate (work(nn*nn))
        allocate (ipiv(nn))
        call zgetrf(nn, nn, A, nn, ipiv, info)
        if (info .ne. 0) then
            print *, 'SEVERE warning: zgetrf failed, info=', info
            A = czero
        else
            call zgetri(nn, A, nn, ipiv, work, nn*nn, info)
            if (info .ne. 0) then
                print *, 'SEVERE warning: zgetri failed, info=', info
                A = czero
            end if
        end if
        deallocate (work)
        deallocate (ipiv)
    end subroutine invert
Call graph
invert calls zgetrf, zgetri
rgf_variableblock_backward calls invert
rgf_variableblock_forward calls invert
sancho calls invert