matrix_alloc2 – Quantum transport simulator
matrix_alloc2 Subroutine
21 statements
Source File
public pure subroutine matrix_alloc2(M, n, source)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(inout) :: M
integer, intent(in) :: n(2)
complex(kind=8), intent(in), optional :: source(1:n(1),1:n(2))
Called by
Contents
Source Code
matrix_alloc2
Source Code
    pure subroutine matrix_alloc2(M, n, source)
        implicit none
        type(type_matrix_complex), intent(inout) :: M
        integer, intent(in):: n(2)
        complex(8), intent(in), optional:: source(1:n(1), 1:n(2))
        if (.not. allocated(M%m)) then
            allocate (M%m(n(1), n(2)))
        else
            if ((M%size(1) == n(1)) .and. (M%size(2) == n(2))) then
            else
                deallocate (M%m)
                allocate (M%m(n(1), n(2)))
            end if
        end if
        if (present(source)) then
            M%m(:, :) = source(:, :)
        else
            M%m(:, :) = dcmplx(0.0d0, 0.0d0)
        end if
        M%size = n
    end subroutine matrix_alloc2
Call graph
malloc calls matrix_alloc2, matrix_alloc, matrix_list_allocelem, matrix_list_allocelem2
matrix_alloc calls matrix_alloc2
matrix_list_allocelem calls matrix_alloc2
matrix_list_allocelem2 calls matrix_alloc2
matrix_read calls matrix_alloc
readtxt calls matrix_read