w90_load_from_file – Quantum transport simulator
w90_load_from_file Subroutine
146 statements
Source File
public subroutine w90_load_from_file(fid, lreorder_axis, axis)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fid
logical, intent(in), optional :: lreorder_axis
integer, intent(in), optional :: axis(3)
Calls
Called by
Contents
Source Code
w90_load_from_file
Source Code
    SUBROUTINE w90_load_from_file(fid, lreorder_axis, axis)
        use, intrinsic :: iso_fortran_env
        include "mpif.h"
        integer, intent(in) :: fid
        logical, intent(in), optional :: lreorder_axis
        integer, intent(in), optional :: axis(3)
        integer :: n, i, nkx, nky, nkz
        character(len=40) :: line, comment
        REAL(8) :: dky, dkz, aux1(3), aux2(3, 3)
        integer, allocatable :: ind(:)
        REAL(8), allocatable :: ham(:, :), energ(:, :), aux3(:, :)
        integer(kind=int32) :: rank
        integer(kind=int32) :: ierror
! Get the individual process (rank)
        call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierror)
        read (fid, *) nvb, spin_deg ! number of VBs, spin-degeneracy
        read (fid, *) comment
        read (fid, *) alpha
        read (fid, *) beta
        read (fid, *) gamm
        cell(:, 1) = alpha
        cell(:, 2) = beta
        cell(:, 3) = gamm
        read (fid, *) comment
        if (present(lreorder_axis) .and. (lreorder_axis)) then
            aux2(:, :) = cell(:, axis)
            cell = aux2
            alpha = cell(:, 1)
            beta = cell(:, 2)
            gamm = cell(:, 3)
        end if
        read (fid, *) n
        allocate (ham(n, 7))
        do i = 1, n
            read (fid, *) ham(i, :)
        end do
        if (present(lreorder_axis) .and. (lreorder_axis)) then
            allocate (aux3(n, 7))
            aux3 = ham
            aux3(:, 1:3) = ham(:, axis)
            ham = aux3
            deallocate (aux3)
        end if
        xmin = minval(ham(:, 1))
        xmax = maxval(ham(:, 1))
        ymin = minval(ham(:, 2))
        ymax = maxval(ham(:, 2))
        zmin = minval(ham(:, 3))
        zmax = maxval(ham(:, 3))
        nb = maxval(ham(:, 4))
        nx = xmax - xmin + 1
        ny = ymax - ymin + 1
        nz = zmax - zmin + 1
        xhat = alpha/norm(alpha)
        yhat = -cross(xhat, gamm)
        yhat = yhat/norm(yhat)
        zhat = gamm/norm(gamm)
        Ly = abs(dot_product(beta, yhat)); ! L is in unit of A
        Lx = abs(dot_product(alpha, xhat));
        Lz = norm(gamm)
        if (rank == 0) then
            print '(A40)', 'reading Wannier H from file, info:'
            print '(8a5)', 'xmin', 'xmax', 'ymin', 'ymax', 'zmin', 'zmax', 'nb', 'nvb'
            print '(8i5)', xmin, xmax, ymin, ymax, zmin, zmax, nb, nvb
            print '(3a5)', 'Lx', 'Ly', 'Lz'
            print '(3f5.1)', Lx, Ly, Lz
        end if
        b1 = cross(beta, gamm)/dot_product(alpha, cross(beta, gamm))
        b2 = cross(gamm, alpha)/dot_product(beta, cross(gamm, alpha))
        allocate (Hr(nb, nb, nx, ny, nz))
        Hr(:, :, :, :, :) = zzero
        do i = 1, n
            Hr(floor(ham(i, 4)), floor(ham(i, 5)), floor(ham(i, 1)) - xmin + 1,&
            &floor(ham(i, 2)) - ymin + 1, floor(ham(i, 3)) - zmin + 1) = ham(i, 6) + z1j*ham(i, 7);
        end do
        !print *, 'Find CBM and VBM'
        nkx = floor((1.0d0/Lx)/0.01d0) + 1
        nky = floor((1.0d0/Ly)/0.01d0) + 1
        nkz = floor((1.0d0/Lz)/0.01d0) + 1
        if (nx == 1) nkx = 1
        if (ny == 1) nky = 1
        if (nz == 1) nkz = 1
        if (ny .eq. 1) then
            nky = 1
        end if
        if (nx .eq. 1) then
            nkx = 1
        end if
        if (nz .eq. 1) then
            nkz = 1
        end if
        if (nky > 1) then
            dky = 1.0d0/dble(nky - 1)*2*pi/Ly
        else
            dky = 2*pi/Ly
        end if
        if (nkz > 1) then
            dkz = 1.0d0/dble(nkz - 1)*2*pi/Lz
        else
            dkz = 2*pi/Lz
        end if
        allocate (energ(nb, nkx*nky*nkz))
        allocate (ind(nb))
        call w90_PLOT_BZ(nkx, nky, nkz, energ)
        ind = maxloc(energ, 2)
        kt_vbm = mod(ind(nvb), nkx)*dky - pi/Ly ! k transverse corresponding to VBMax
        ind = minloc(energ, 2)
        kt_cbm = mod(ind(nvb + 1), nkx)*dky - pi/Ly ! k transverse corresponding to CBM
        if (ny .eq. 1) then
            kt_cbm = 0.0d0
            kt_vbm = 0.0d0
        end if
        ind = maxloc(energ, 2)
        VBM = energ(nvb, ind(nvb))
        ind = minloc(energ, 2)
        CBM = energ(nvb + 1, ind(nvb + 1))
        Eg = CBM - VBM
        if (rank == 0) then
            print '(3A8)', 'CBM', 'VBM', 'Eg'
            print '(3f8.3)', CBM, VBM, CBM - VBM
            print '(3A8)', 'kt_CBM', 'kt_VBM', '2pi/Ly'
            print '(2f8.3)', kt_cbm/(2.0*pi/Ly), kt_vbm/(2.0*pi/Ly)
            print '(A40)', 'reading Wannier centers from file'
        end if
        read (fid, *) comment
        allocate (wannier_center(3, nb))
        do i = 1, nb
            read (fid, *) wannier_center(:, i)
        end do
        if (present(lreorder_axis) .and. (lreorder_axis)) then
            allocate (aux3(3, nb))
            aux3 = wannier_center
            aux3(1:3, :) = wannier_center(axis, :)
            wannier_center = aux3
            deallocate (aux3)
        end if
        ! bring wannier_center into the first unit-cell, only works for orth.
        ! to-do: make this general
        do i = 1, NB
            if (wannier_center(1, i) < 0) wannier_center(:, i) = wannier_center(:, i) + alpha
            if (wannier_center(1, i) > Lx) wannier_center(:, i) = wannier_center(:, i) - alpha
            if (wannier_center(2, i) < 0) wannier_center(:, i) = wannier_center(:, i) + beta
            if (wannier_center(2, i) > Ly) wannier_center(:, i) = wannier_center(:, i) - beta
            if (wannier_center(3, i) < 0) wannier_center(:, i) = wannier_center(:, i) + gamm
            if (wannier_center(3, i) > Lz) wannier_center(:, i) = wannier_center(:, i) - gamm
        end do
        ! center z around 0
        wannier_center(3, :) = wannier_center(3, :) - (sum(wannier_center(3, :)/dble(NB)))
        deallocate (ham)
        deallocate (energ)
        deallocate (ind)
    END SUBROUTINE w90_load_from_file
Call graph
w90_load_from_file calls mpi_comm_rank, cross, norm
devh_build_fromwannierfile calls w90_load_from_file
main calls devh_build_fromwannierfile