DftiSetValue – Quantum transport simulator
DftiSetValue Interface
37 statements
Source File
public interface DftiSetValue
Called by
Contents
Functions
dfti_set_value_intval dfti_set_value_sglval dfti_set_value_dblval dfti_set_value_intvec dfti_set_value_chars
Functions
public function dfti_set_value_intval(desc, OptName, IntVal)
Arguments
Type Intent Optional Attributes Name
type(DFTI_DESCRIPTOR), POINTER :: desc
integer, intent(in) :: OptName
integer, intent(in) :: IntVal
Return Value integer
public function dfti_set_value_sglval(desc, OptName, sglval)
Arguments
Type Intent Optional Attributes Name
type(DFTI_DESCRIPTOR), POINTER :: desc
integer, intent(in) :: OptName
real(kind=DFTI_SPKP), intent(in) :: sglval
Return Value integer
public function dfti_set_value_dblval(desc, OptName, DblVal)
Arguments
Type Intent Optional Attributes Name
type(DFTI_DESCRIPTOR), POINTER :: desc
integer, intent(in) :: OptName
real(kind=DFTI_DPKP), intent(in) :: DblVal
Return Value integer
public function dfti_set_value_intvec(desc, OptName, IntVec)
Arguments
Type Intent Optional Attributes Name
type(DFTI_DESCRIPTOR), POINTER :: desc
integer, intent(in) :: OptName
integer, intent(in), DIMENSION(*) :: IntVec
Return Value integer
public function dfti_set_value_chars(desc, OptName, Chars)
Arguments
Type Intent Optional Attributes Name
type(DFTI_DESCRIPTOR), POINTER :: desc
integer, intent(in) :: OptName
character(len=*), intent(in) :: Chars
Return Value integer
Call graph
do_mkl_dfti_conv calls dftisetvalue
conv1d calls do_mkl_dfti_conv
conv1d2 calls do_mkl_dfti_conv
corr1d calls do_mkl_dfti_conv
corr1d2 calls do_mkl_dfti_conv