malloc – Quantum transport simulator
malloc Interface
4 statements
Source File
public interface malloc
Calls
Contents
Module Procedures
matrix_list_allocElem2 matrix_list_allocElem matrix_alloc matrix_alloc2 array_alloc array_alloc2
Module Procedures
public pure subroutine matrix_list_allocElem2(this, nx, n, source)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(out) :: this(1:nx)
integer, intent(in) :: nx
integer, intent(in) :: n(2,1:nx)
complex(kind=8), intent(in), optional :: source(:,:,:)
the source data to put into the matrices
public pure subroutine matrix_list_allocElem(this, nx, nm, nn, source)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(out) :: this(1:nx)
integer, intent(in) :: nx
integer, intent(in) :: nm(1:nx)
integer, intent(in), optional :: nn(1:nx)
complex(kind=8), intent(in), optional :: source(:,:,:)
the source data to put into the matrices
public pure subroutine matrix_alloc(M, n, nn, source)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(out) :: M
integer, intent(in) :: n
integer, intent(in), optional :: nn
complex(kind=8), intent(in), optional :: source(:,:)
public pure subroutine matrix_alloc2(M, n, source)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(out) :: M
integer, intent(in) :: n(2)
complex(kind=8), intent(in), optional :: source(1:n(1),1:n(2))
public pure subroutine array_alloc(M, n, nn)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(out), allocatable :: M(:,:)
integer, intent(in) :: n
integer, intent(in), optional :: nn
public pure subroutine array_alloc2(M, n)
This function allocates a 2D complex array. If the array is already allocated, this function will resize the array to the new size. The allocated array is initiated to zero.
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(out), allocatable :: M(:,:)
integer, intent(in) :: n(2)
Call graph
malloc calls array_alloc, array_alloc2, matrix_alloc, matrix_alloc2, matrix_list_allocelem, matrix_list_allocelem2
array_alloc calls array_alloc2
matrix_alloc calls matrix_alloc2
matrix_list_allocelem calls matrix_alloc2
matrix_list_allocelem2 calls matrix_alloc2