operator(**) – Quantum transport simulator
operator(**) Interface
3 statements
Source File
public interface operator(**)
Calls
Contents
Module Procedures
array_power array_transpose
Module Procedures
public function array_power(A, n) result(C)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: A(:,:)
integer, intent(in) :: n
Return Value complex(kind=8), (size(A,1),size(A,1))
public pure function array_transpose(A, t) result(C)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: A(:,:)
character(len=1), intent(in) :: t
Return Value complex(kind=8), (size(A,2),size(A,1))
Call graph
operator(ASTERISKASTERISK) calls array_power, array_transpose
array_power calls array_eye, array_inverse
array_inverse calls zgetrf, zgetri