sizeof – Quantum transport simulator
sizeof Interface
3 statements
Source File
public interface sizeof
Calls
Contents
Module Procedures
array_size matrix_size matrix_list_size matrix_size_dim matrix_list_size2
Module Procedures
public pure function array_size(this) result(s)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: this(:,:)
Return Value integer, (2)
public pure function matrix_size(this) result(s)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(in) :: this
Return Value integer, (2)
public pure function matrix_list_size(list, dim) result(nm)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(in) :: list(:)
integer, intent(in) :: dim
Return Value integer, (size(list))
public pure function matrix_size_dim(this, dim) result(s)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(in) :: this
integer, intent(in) :: dim
Return Value integer
public pure function matrix_list_size2(list) result(nm)
Arguments
Type Intent Optional Attributes Name
type(type_matrix_complex), intent(in) :: list(:)
Return Value integer, (2,size(list))
Call graph
sizeof calls array_size, matrix_list_size, matrix_list_size2, matrix_size, matrix_size_dim